In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array.shape

(9,)

In [5]:
array_mod = array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array_mod2 = array.reshape(-1,3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array_volteado = array_mod2.transpose()
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
array_plano = array_mod.flatten()
array_plano

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])