In [1]:
import numpy as np

In [2]:
array1d = np.array([1, 2, 3, 4, 5])

In [3]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [4]:
array1d[0]

1

In [5]:
array1d[-1]

5

In [6]:
array2d[0]

array([1, 2, 3])

In [7]:
array2d[0,0]

1

In [8]:
array1d[1:4]

array([2, 3, 4])

In [9]:
array2d[0:1,0:1]

array([[1]])

In [10]:
array2d[0:1,0:2]

array([[1, 2]])

In [11]:
array2d[1,:]

array([4, 5, 6])

In [12]:
array2d[:,1]

array([2, 5, 8])

In [13]:
array2d[0:1,0:2]

array([[1, 2]])

In [14]:
array2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [15]:
array1d > 3

array([False, False, False,  True,  True])

In [16]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])