In [1]:
import numpy as np

In [8]:
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [3]:
np.isnan(array)

array([False, False,  True, False, False, False])

In [4]:
np.mean(array)

nan

In [5]:
np.nanmean(array)

3.0

In [6]:
array_con_0 = np.where(np.isnan(array),0,array)
array_con_0

array([1., 2., 0., 3., 4., 5.])

In [9]:
promedio = np.nanmean(array)
array_con_promedio = np.where(np.isnan(array),promedio,array)
array_con_promedio

array([1., 2., 3., 4., 5.])

In [11]:
array_filtrado = array[~np.isnan(array)]
array_filtrado

array([1., 2., 4., 5.])